# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: 'npm' # See documentation for possible values
    directory: '/' # Location of package manifests
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 10
    groups:
      nestjs-ecosystem:
        patterns:
          - '@nestjs/*'
        update-types:
          - 'major'
          - 'minor'
          - 'patch'
      prisma-ecosystem:
        patterns:
          - '@prisma/*'
          - 'prisma'
          - 'prisma-dbml-generator'
        update-types:
          - 'major'
          - 'minor'
          - 'patch'
      code-quality-tools:
        patterns:
          - '@eslint/*'
          - 'eslint*'
          - 'prettier'
          - '@typescript-eslint/*'
        update-types:
          - 'major'
          - 'minor'
          - 'patch'
      testing-tools:
        patterns:
          - 'jest*'
          - '@types/jest'
          - 'ts-jest'
          - 'supertest'
          - '@types/supertest'
        update-types:
          - 'major'
          - 'minor'
          - 'patch'
      typescript-ecosystem:
        patterns:
          - 'typescript'
          - 'typescript-eslint'
          - '@types/*'
          - 'ts-*'
        update-types:
          - 'major'
          - 'minor'
          - 'patch'
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
